
- [287.md](0-system-findings/1-processed/0-false/287.md): #false
  - **Description:** Wrongly checked return value of a external call
  - **Reason:** This is a non-issue, and it is the intended behavior of the `finalizeWithdrawalTransaction` function. The `finalizeWithdrawalTransaction` function should **not** revert if the withdrawal transaction fails via `SafeCall`- it is up to the initiator of the withdrawal transaction to ensure the minimum gas limit is sufficient to execute the withdrawal transaction on L1. The revert if the tx origin is the `ESTIMATION_ADDRESS` is present only to assist with gas estimation on the front-end.

---

0xWeiss

high

# # [H-02] Wrongly checked return value of a external call

## Summary

In https://github.com/sherlock-audit/2023-01-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L341

the function finalizeWithdrawal:

        bool success = SafeCall.call(
            _tx.target,
            gasleft() - FINALIZE_GAS_BUFFER,
            _tx.value,
            _tx.data
        );

        // Reset the l2Sender back to the default value.
        l2Sender = Constants.DEFAULT_L2_SENDER;
        emit WithdrawalFinalized(withdrawalHash, success);

        if (success == false && tx.origin == Constants.ESTIMATION_ADDRESS) {
            revert("OptimismPortal: withdrawal failed");
        }
    }

    the problem resides in the following line:

        if (success == false && tx.origin == Constants.ESTIMATION_ADDRESS) {

which means that if the external call fails, it will revert only if the tx.origin is the estimation address. 

## Vulnerability Detail
This is wrong because the estimation address is used only for gas estimation. So, if the external call fails, it will revert only if the tx.origin is the estimation address. So the external call can fail and the ether will be lost forever. Or/and this opens more attack vectors to make fail the external call intentionally.

## Impact

It can definitely cause loss of funds of ether sent to contract which can't receive it. And it can open more attack vectors y making the external call fail intentionally.

## Code Snippet
In https://github.com/sherlock-audit/2023-01-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol?plain=1#L341

## Tool used 
Manual Review


## Recommendation

Change the line to:

        if (success == false) {
            revert("OptimismPortal: withdrawal failed");
            }